# FROM alpine:3.15
FROM ghcr.io/hellt/network-multitool

RUN apk add --no-cache keepalived lldpd iperf3 bonding vlan tcpdump paris-traceroute sudo
# sed -i '3 i /usr/sbin/lldpd' /usr/lib/frr/docker-start
# sed -i '3 i /sbin/ifup -a' /usr/lib/frr/docker-start

# Remove default keepalived config file
RUN rm -rf /etc/keepalived/keepalived.conf

COPY --chown=root:root Docker/alpine_startup.sh /alpine_startup.sh

ENTRYPOINT ["/alpine_startup.sh"]
