FROM frrouting/frr:latest

#RUN apk add openrc open-lldp && \
# echo 'lldp : { eth1 : { adminStatus = 3; tlvid00000005 : { enableTx = true; };}; };' >> /var/lib/lldpad/lldpad.conf && \
# sed -i 's|set -e$|set -e;/usr/sbin/lldpad -d|g' /usr/lib/frr/docker-start

RUN apk add --no-cache lldpd iperf3 bonding && \
 sed -i '3 i /usr/sbin/lldpd' /usr/lib/frr/docker-start
 # sed -i '3 i /sbin/ifup -a' /usr/lib/frr/docker-start

COPY --chown=root:root Docker/daemons /etc/frr
